//! Configuration (`docs/design-mint.md` § *Mint configuration*). v1 is
//! single-tenant, single-root-key.
//!
//! Audience, tenant, and role metadata are file-backed (TOML); the
//! macaroon root key is not config (generated by [`crate::state::Store`]
//! at `<data_dir>/root_key`). Each role's IAM-policy template lives in
//! its own file under
//! `roles_dir`, named by the role's `policy_file` (a single normal path
//! component — see [`read_policy`]). The Tigris admin credential is the
//! one input that comes from the environment — `AWS_*`, resolved by
//! [`AdminCredential::from_env`] at load — never the TOML, so secrets
//! and role definitions stay on separate management planes.

use std::collections::BTreeMap;
use std::net::SocketAddr;
use std::path::{Component, Path, PathBuf};

use serde::Deserialize;

#[derive(Debug, thiserror::Error)]
pub enum ConfigError {
    #[error("read config: {0}")]
    Io(#[from] std::io::Error),
    #[error("parse config: {0}")]
    Toml(#[from] toml::de::Error),
    #[error("duplicate role name: {0}")]
    DuplicateRole(String),
    #[error("role {role}: {field} must be > 0 and min <= default <= max")]
    BadTtlBounds { role: String, field: String },
    #[error(
        "role {role}: policy_file {value:?} must be a single filename \
         (no path separators, no '.' or '..', not absolute)"
    )]
    BadPolicyFileName { role: String, value: String },
    #[error(
        "role {role}: derived policy filename {value:?} is not a single \
         filename — set an explicit policy_file or rename the role"
    )]
    BadDerivedPolicyName { role: String, value: String },
    #[error("role {role}: read policy_file {path}: {source}")]
    ReadPolicyFile {
        role: String,
        path: String,
        #[source]
        source: std::io::Error,
    },
    #[error(
        "bind and socket are mutually exclusive — set one (TCP) or the \
         other (UDS), not both"
    )]
    ConflictingListener,
    #[error("bind {value:?} is not a valid host:port: {source}")]
    BadBindAddr {
        value: String,
        #[source]
        source: std::net::AddrParseError,
    },
    #[error(
        "role {0} has issues_with_tpc = true but no [auth] block is configured; \
         set [auth].endpoint or remove the TPC requirement from this role"
    )]
    TpcRoleWithoutAuth(String),
}

#[derive(Debug, Deserialize)]
pub struct RawConfig {
    /// The audience name this mint answers to. A macaroon whose
    /// `Audience` caveat differs is rejected (cross-service replay
    /// defence).
    pub audience: String,
    /// Directory for mint's persisted state — the macaroon root key
    /// (`root_key`, generated on first start), the current invite
    /// nonce, and the transient pending-enrollment table, all under one
    /// custody (`docs/design-mint.md` § *Enrollment*, § *Mint
    /// configuration*). A relative value
    /// (including the default `mint_data`) resolves against the current
    /// working directory, not the config file's parent — the same rule
    /// the elide coordinator uses for `data_dir`; an absolute path is
    /// used verbatim.
    #[serde(default)]
    pub data_dir: Option<String>,
    /// Directory holding role policy-template files, one per role
    /// (referenced by each role's `policy_file`). Same resolution rule
    /// as `data_dir`; defaults to `mint_roles`.
    #[serde(default)]
    pub roles_dir: Option<String>,
    /// TCP listener address (`host:port`). The network deployment
    /// shapes — self-hosted on a separate trusted machine, central
    /// custodial/proxy — all use this; TLS is terminated ahead of or by
    /// mint. Mutually exclusive with `socket`. When neither is set the
    /// listener defaults to TCP `127.0.0.1:8085`.
    #[serde(default)]
    pub bind: Option<String>,
    /// Unix-domain-socket listener path — the bundled single-host dev
    /// shape (coordinator + mint co-resident, matching `coord run` /
    /// `coord start`). Selecting it is what makes a mint instance
    /// local-only: no port, no accidental network exposure, no
    /// same-host TLS, filesystem-permission scoped. Mutually exclusive
    /// with `bind`. Same resolution rule as `data_dir` (relative
    /// against cwd, absolute verbatim); an empty value selects UDS at
    /// the default `<data_dir>/mint.sock`.
    #[serde(default)]
    pub socket: Option<String>,
    pub tenant: Tenant,
    /// Auth-service integration. Optional: a mint configured without
    /// `[auth]` cannot stamp third-party caveats and refuses
    /// `assume-role` for any role that has `issues_with_tpc = true`.
    /// See `docs/design-auth-service.md`.
    #[serde(default)]
    pub auth: Option<RawAuth>,
    #[serde(rename = "role", default)]
    pub roles: Vec<RawRole>,
}

/// `[auth]` block: where third-party caveats point and whether mint
/// itself rubber-stamps the auth-service routes (`demo_enabled`).
#[derive(Debug, Clone, Deserialize)]
pub struct RawAuth {
    /// Auth service URL, surfaced as the `location` of every TPC mint
    /// stamps and returned to coords on the 401 challenge response.
    /// Required when `[auth]` is present.
    pub endpoint: String,
    /// When `true`, mint mounts the auth-service route handlers
    /// itself (`/v1/login/*`, `/v1/discharge`) and rubber-stamps every
    /// login. Generates `K_M-A` and `K_session` on first start. Demo /
    /// test only. Mint refuses to start with `demo_enabled = true`
    /// unless it is bound to loopback or UDS — see
    /// `docs/design-auth-service.md` § *Mint as auth (demo only)*.
    #[serde(default)]
    pub demo_enabled: bool,
}

#[derive(Debug, Clone, Deserialize)]
pub struct Tenant {
    /// Bucket name; surfaced to templates as `{{tenant.bucket}}`.
    pub bucket: String,
    /// S3 endpoint URL. Used by `serve --tigris` to build the
    /// data-plane client that reads and writes `_mint/*` under
    /// [self-vended `mint-rw` credentials][mint-rw], distinct from
    /// the IAM endpoint that `tigris.rs` calls. Omit to use Tigris's
    /// default S3 endpoint
    /// ([`crate::mint_rw::DEFAULT_TIGRIS_S3_ENDPOINT`]); set
    /// explicitly only for a non-Tigris S3-compatible target
    /// (custom AWS region, MinIO, etc.).
    ///
    /// [mint-rw]: crate::state::Store
    #[serde(default)]
    pub endpoint: Option<String>,
    /// S3 region; defaults to `us-east-1` (which Tigris accepts as a
    /// no-op). Override only for non-Tigris S3-compatible backends that
    /// reject the default.
    #[serde(default)]
    pub region: Option<String>,
}

/// Tigris admin credential, read from the standard AWS environment
/// variables — the same convention the elide coordinator uses for its
/// IAM-mode admin credential. It is deliberately **not** in the TOML
/// config: the credential is a secret delivered by the environment
/// (systemd `LoadCredential=`, a secrets manager, …), never committed
/// alongside role definitions.
#[derive(Clone)]
pub struct AdminCredential {
    pub access_key_id: String,
    pub secret_access_key: String,
    /// `AWS_SESSION_TOKEN` if present (STS-style temporary creds).
    pub session_token: Option<String>,
}

impl std::fmt::Debug for AdminCredential {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Never render the secret — only that a credential is present.
        f.debug_struct("AdminCredential")
            .field("access_key_id", &self.access_key_id)
            .field("secret_access_key", &"<redacted>")
            .field(
                "session_token",
                &self.session_token.as_ref().map(|_| "<redacted>"),
            )
            .finish()
    }
}

impl AdminCredential {
    /// Resolve from `AWS_ACCESS_KEY_ID` / `AWS_SECRET_ACCESS_KEY`
    /// (+ optional `AWS_SESSION_TOKEN`). `None` if either required var
    /// is unset or empty — the prototype's faked minter does not need
    /// it, so absence is a warning at startup, not a hard error.
    pub fn from_env() -> Option<Self> {
        let access_key_id = non_empty_env("AWS_ACCESS_KEY_ID")?;
        let secret_access_key = non_empty_env("AWS_SECRET_ACCESS_KEY")?;
        Some(Self {
            access_key_id,
            secret_access_key,
            session_token: non_empty_env("AWS_SESSION_TOKEN"),
        })
    }
}

fn non_empty_env(key: &str) -> Option<String> {
    std::env::var(key).ok().filter(|v| !v.is_empty())
}

#[derive(Debug, Deserialize)]
pub struct RawRole {
    pub name: String,
    #[serde(default)]
    pub required_caveats: Vec<String>,
    pub min_ttl_seconds: u64,
    pub max_ttl_seconds: u64,
    pub default_ttl_seconds: u64,
    /// Filename of the IAM-policy handlebars template (see
    /// [`crate::template`]), resolved against `roles_dir`. Optional;
    /// defaults to `<name>.json`. Whether explicit or derived it must
    /// be a single normal path component — validated by [`read_policy`]
    /// (so a role `name` with a path separator is rejected too).
    #[serde(default)]
    pub policy_file: Option<String>,
    /// Whether mint appends a third-party caveat to every credential
    /// it mints for this role. Drives the operator-initiated vs
    /// background split (`docs/design-mint.md` § *Elide as customer*
    /// and `docs/design-auth-service.md`): operator-write roles set
    /// `true`; read roles and background-write variants leave it
    /// `false`. Issuance unconditionally appends the TPC when set;
    /// verification unconditionally requires a discharge for any TPC
    /// it walks.
    #[serde(default)]
    pub issues_with_tpc: bool,
}

/// Resolved listener transport — a per-deployment-shape choice, not a
/// global default (`docs/design-mint.md` § *Transport*). The macaroon +
/// Ed25519 PoP auth is identical over either; the socket neither
/// weakens nor substitutes for it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Listener {
    /// The network shapes. TLS terminated ahead of or by mint.
    Tcp(SocketAddr),
    /// The single-host dev shape. Recreated on bind (stale dentry
    /// removed first), chmod `0o666` so a non-root coordinator can
    /// connect.
    Uds(PathBuf),
}

/// Default TCP listener when neither `bind` nor `socket` is configured.
pub const DEFAULT_BIND: &str = "127.0.0.1:8085";
/// Socket filename under `data_dir` when `socket` is selected without
/// an explicit path.
pub const DEFAULT_SOCKET_NAME: &str = "mint.sock";

/// Auth-service settings, post-validation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Auth {
    pub endpoint: String,
    pub demo_enabled: bool,
}

/// Validated configuration, ready to serve.
#[derive(Debug)]
pub struct Config {
    pub audience: String,
    /// Persisted-state directory: the root key (generated on first
    /// start), invite nonce, and pending table all share this
    /// custody. Defaults to `mint_data` when the config omits
    /// `data_dir`. The root key itself is owned by
    /// [`crate::state::Store`], not parsed from config.
    pub data_dir: PathBuf,
    /// Directory the role `policy_file`s were read from. Defaults to
    /// `mint_roles`. Retained for diagnostics; policies are already
    /// resolved into [`Role::policy`].
    pub roles_dir: PathBuf,
    /// The resolved listener transport. The CLI may still override this
    /// with an explicit `--bind` (the TCP single-host override).
    pub listener: Listener,
    pub tenant: Tenant,
    /// Resolved from the AWS environment at load time. `None` when the
    /// env is unset. `mint serve` requires `Some`; tests that
    /// construct `Config` directly (and use `Store::open_local` /
    /// `Store::open_in_memory` instead of the Tigris backend) can
    /// leave it `None`.
    pub admin: Option<AdminCredential>,
    /// Auth-service settings — `None` if the config omits `[auth]`.
    /// A mint without auth cannot stamp TPCs; roles with
    /// `issues_with_tpc = true` are refused at startup.
    pub auth: Option<Auth>,
    pub roles: BTreeMap<String, Role>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Role {
    pub name: String,
    pub required_caveats: Vec<String>,
    pub min_ttl_seconds: u64,
    pub max_ttl_seconds: u64,
    pub default_ttl_seconds: u64,
    /// The resolved source of [`policy`](Role::policy):
    /// `<roles_dir>/<policy_file>`, or `<roles_dir>/<name>.json` when no
    /// explicit `policy_file` was set. Retained for diagnostics
    /// (`mint role inspect`); the template itself is already resolved.
    pub policy_path: PathBuf,
    /// The role's IAM-policy handlebars template, read from
    /// [`policy_path`](Role::policy_path) at load.
    pub policy: String,
    /// When `true`, mint appends a third-party caveat (see
    /// `docs/design-auth-service.md`) to every credential it mints
    /// for this role. The TPC location is the configured auth
    /// service; verification of the resulting credential at
    /// `assume-role` requires a matching discharge.
    pub issues_with_tpc: bool,
}

impl Config {
    pub fn from_toml_str(s: &str) -> Result<Config, ConfigError> {
        Self::from_raw(toml::from_str(s)?)
    }

    pub fn load(path: &Path) -> Result<Config, ConfigError> {
        Self::from_toml_str(&std::fs::read_to_string(path)?)
    }

    fn from_raw(raw: RawConfig) -> Result<Config, ConfigError> {
        let roles_dir = raw
            .roles_dir
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from("mint_roles"));
        let mut roles = BTreeMap::new();
        for r in raw.roles {
            if r.min_ttl_seconds == 0
                || r.min_ttl_seconds > r.default_ttl_seconds
                || r.default_ttl_seconds > r.max_ttl_seconds
            {
                return Err(ConfigError::BadTtlBounds {
                    role: r.name.clone(),
                    field: "ttl_seconds".into(),
                });
            }
            let (policy_path, policy) = match r.policy_file {
                Some(ref f) => read_policy(&roles_dir, &r.name, f, true)?,
                None => read_policy(&roles_dir, &r.name, &format!("{}.json", r.name), false)?,
            };
            let role = Role {
                name: r.name.clone(),
                required_caveats: r.required_caveats,
                min_ttl_seconds: r.min_ttl_seconds,
                max_ttl_seconds: r.max_ttl_seconds,
                default_ttl_seconds: r.default_ttl_seconds,
                policy_path,
                policy,
                issues_with_tpc: r.issues_with_tpc,
            };
            if roles.insert(r.name.clone(), role).is_some() {
                return Err(ConfigError::DuplicateRole(r.name));
            }
        }
        let data_dir = raw
            .data_dir
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from("mint_data"));
        let listener = resolve_listener(raw.bind.as_deref(), raw.socket.as_deref(), &data_dir)?;
        let auth = raw.auth.map(|a| Auth {
            endpoint: a.endpoint,
            demo_enabled: a.demo_enabled,
        });
        // A role that requires a TPC needs an `[auth]` block to point
        // it at. Refusing here keeps the issuance path
        // unconditional (it always finds an auth endpoint when
        // `issues_with_tpc` is true).
        if auth.is_none()
            && let Some(r) = roles.values().find(|r| r.issues_with_tpc)
        {
            return Err(ConfigError::TpcRoleWithoutAuth(r.name.clone()));
        }
        Ok(Config {
            audience: raw.audience,
            data_dir,
            roles_dir,
            listener,
            tenant: raw.tenant,
            admin: AdminCredential::from_env(),
            auth,
            roles,
        })
    }
}

/// Resolve the listener transport from the mutually-exclusive `bind` /
/// `socket` keys (`docs/design-mint.md` § *Transport*):
///
/// - both set → [`ConfigError::ConflictingListener`];
/// - `socket` non-empty → UDS at that path (relative against cwd,
///   absolute verbatim — the `data_dir` rule);
/// - `socket` present but empty → UDS at `<data_dir>/mint.sock`;
/// - `bind` set → TCP at that parsed address;
/// - neither → TCP at [`DEFAULT_BIND`] (the production default;
///   selecting the socket is the deliberate act that makes an instance
///   local-only).
fn resolve_listener(
    bind: Option<&str>,
    socket: Option<&str>,
    data_dir: &Path,
) -> Result<Listener, ConfigError> {
    match (bind, socket) {
        (Some(_), Some(_)) => Err(ConfigError::ConflictingListener),
        (None, Some(s)) => Ok(Listener::Uds(if s.is_empty() {
            data_dir.join(DEFAULT_SOCKET_NAME)
        } else {
            PathBuf::from(s)
        })),
        (Some(b), None) => parse_bind(b).map(Listener::Tcp),
        (None, None) => parse_bind(DEFAULT_BIND).map(Listener::Tcp),
    }
}

fn parse_bind(value: &str) -> Result<SocketAddr, ConfigError> {
    value.parse().map_err(|source| ConfigError::BadBindAddr {
        value: value.to_owned(),
        source,
    })
}

/// Read a role's policy template from `<roles_dir>/<policy_file>`.
///
/// `policy_file` is parsed, not substring-checked: `Path::new` of it
/// must yield exactly one [`Component::Normal`]. That rejects path
/// separators, absolute paths, `.`, `..`, parent traversal, and the
/// empty string in one predicate, so a role name cannot reach outside
/// `roles_dir`. The guarantee is name-level — a symlink *inside*
/// `roles_dir` is still followed, but `roles_dir` shares the config's
/// custody, so its contents are the operator's own.
///
/// `explicit` selects the diagnostic: a bad *explicit* `policy_file` is
/// [`ConfigError::BadPolicyFileName`]; a bad *derived* `<name>.json`
/// (i.e. an unsafe role name) is [`ConfigError::BadDerivedPolicyName`].
fn read_policy(
    roles_dir: &Path,
    role: &str,
    policy_file: &str,
    explicit: bool,
) -> Result<(PathBuf, String), ConfigError> {
    let mut comps = Path::new(policy_file).components();
    let only = comps.next();
    if comps.next().is_some() || !matches!(only, Some(Component::Normal(_))) {
        let (role, value) = (role.to_owned(), policy_file.to_owned());
        return Err(if explicit {
            ConfigError::BadPolicyFileName { role, value }
        } else {
            ConfigError::BadDerivedPolicyName { role, value }
        });
    }
    let path = roles_dir.join(policy_file);
    let contents =
        std::fs::read_to_string(&path).map_err(|source| ConfigError::ReadPolicyFile {
            role: role.to_owned(),
            path: path.display().to_string(),
            source,
        })?;
    Ok((path, contents))
}

/// Path-A test harness (shared with `role.rs`'s unit tests): write each
/// role policy into a tempdir, splice an absolute `roles_dir` into the
/// TOML, then exercise the real [`Config::from_toml_str`] file-read
/// path. The tempdir only needs to outlive the parse — `policy` is read
/// eagerly — so it is dropped on return.
#[cfg(test)]
pub(crate) fn parse_for_test(toml: &str, roles: &[(&str, &str)]) -> Result<Config, ConfigError> {
    let dir = tempfile::tempdir().expect("tempdir");
    for (name, body) in roles {
        std::fs::write(dir.path().join(name), body).expect("write role file");
    }
    let injected = toml.replacen(
        "[tenant]",
        &format!(
            "roles_dir = {:?}\n[tenant]",
            dir.path().display().to_string()
        ),
        1,
    );
    Config::from_toml_str(&injected)
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"
audience = "mint"

[tenant]
bucket = "demo-bucket"

[[role]]
name = "volume-ro"
required_caveats = ["elide:Volume", "Audience", "NotAfter"]
min_ttl_seconds = 60
max_ttl_seconds = 2592000
default_ttl_seconds = 2592000
policy_file = "volume-ro.json"
"#;

    #[test]
    fn parses_sample() {
        let c = parse_for_test(SAMPLE, &[("volume-ro.json", "{}")]).expect("parse");
        assert_eq!(c.audience, "mint");
        assert_eq!(c.tenant.bucket, "demo-bucket");
        assert_eq!(c.roles["volume-ro"].policy, "{}");
    }

    #[test]
    fn rejects_inverted_ttl_bounds() {
        let bad = SAMPLE.replace("max_ttl_seconds = 2592000", "max_ttl_seconds = 10");
        assert!(matches!(
            parse_for_test(&bad, &[("volume-ro.json", "{}")]),
            Err(ConfigError::BadTtlBounds { .. })
        ));
    }

    #[test]
    fn rejects_policy_file_traversal() {
        // Name validation fires before any read, so roles_dir is never
        // touched — no file is written.
        for evil in ["../escape.json", "/etc/passwd", "a/b.json", "..", "."] {
            let toml = SAMPLE
                .replace("[tenant]", "roles_dir = \"mint_roles\"\n[tenant]")
                .replace("volume-ro.json", evil);
            assert!(
                matches!(
                    Config::from_toml_str(&toml),
                    Err(ConfigError::BadPolicyFileName { .. })
                ),
                "expected BadPolicyFileName for {evil:?}"
            );
        }
    }

    #[test]
    fn rejects_missing_policy_file() {
        let dir = tempfile::tempdir().expect("tempdir");
        let toml = SAMPLE.replace(
            "[tenant]",
            &format!(
                "roles_dir = {:?}\n[tenant]",
                dir.path().display().to_string()
            ),
        );
        assert!(matches!(
            Config::from_toml_str(&toml),
            Err(ConfigError::ReadPolicyFile { .. })
        ));
    }

    #[test]
    fn issues_with_tpc_defaults_to_false() {
        let c = parse_for_test(SAMPLE, &[("volume-ro.json", "{}")]).expect("parse");
        assert!(!c.roles["volume-ro"].issues_with_tpc);
    }

    /// Inject an `[auth]` block before the first `[[role]]` in
    /// SAMPLE. Injecting at `[tenant]` would land `parse_for_test`'s
    /// `roles_dir = ...` line inside the `[auth]` table after my
    /// replacement; injecting at `[[role]]` keeps every key in the
    /// right table.
    fn with_auth(s: &str, body: &str) -> String {
        s.replacen("[[role]]", &format!("[auth]\n{body}\n\n[[role]]"), 1)
    }

    #[test]
    fn issues_with_tpc_is_parsed() {
        let toml = with_auth(
            &SAMPLE.replace(
                "policy_file = \"volume-ro.json\"",
                "policy_file = \"volume-ro.json\"\nissues_with_tpc = true",
            ),
            "endpoint = \"https://auth.example/\"",
        );
        let c = parse_for_test(&toml, &[("volume-ro.json", "{}")]).expect("parse");
        assert!(c.roles["volume-ro"].issues_with_tpc);
        assert!(c.auth.is_some());
    }

    #[test]
    fn tpc_role_without_auth_block_is_rejected() {
        let toml = SAMPLE.replace(
            "policy_file = \"volume-ro.json\"",
            "policy_file = \"volume-ro.json\"\nissues_with_tpc = true",
        );
        assert!(matches!(
            parse_for_test(&toml, &[("volume-ro.json", "{}")]),
            Err(ConfigError::TpcRoleWithoutAuth(role)) if role == "volume-ro"
        ));
    }

    #[test]
    fn auth_block_is_parsed() {
        let toml = with_auth(
            SAMPLE,
            "endpoint = \"https://auth.example/\"\ndemo_enabled = true",
        );
        let c = parse_for_test(&toml, &[("volume-ro.json", "{}")]).expect("parse");
        let auth = c.auth.expect("auth present");
        assert_eq!(auth.endpoint, "https://auth.example/");
        assert!(auth.demo_enabled);
    }

    #[test]
    fn auth_demo_enabled_defaults_to_false() {
        let toml = with_auth(SAMPLE, "endpoint = \"https://auth.example/\"");
        let c = parse_for_test(&toml, &[("volume-ro.json", "{}")]).expect("parse");
        let auth = c.auth.expect("auth present");
        assert!(!auth.demo_enabled);
    }

    #[test]
    fn policy_file_defaults_to_name_json() {
        // Drop the explicit policy_file: it must derive `<name>.json`.
        let toml = SAMPLE.replace("policy_file = \"volume-ro.json\"\n", "");
        let c = parse_for_test(&toml, &[("volume-ro.json", "{}")]).expect("parse");
        assert_eq!(c.roles["volume-ro"].policy, "{}");
    }

    #[test]
    fn listener_defaults_to_tcp_8085() {
        let c = parse_for_test(SAMPLE, &[("volume-ro.json", "{}")]).expect("parse");
        assert_eq!(c.listener, Listener::Tcp("127.0.0.1:8085".parse().unwrap()));
    }

    #[test]
    fn explicit_bind_is_parsed() {
        let toml = SAMPLE.replace(
            "audience = \"mint\"",
            "audience = \"mint\"\nbind = \"0.0.0.0:9000\"",
        );
        let c = parse_for_test(&toml, &[("volume-ro.json", "{}")]).expect("parse");
        assert_eq!(c.listener, Listener::Tcp("0.0.0.0:9000".parse().unwrap()));
    }

    #[test]
    fn bad_bind_is_rejected() {
        let toml = SAMPLE.replace(
            "audience = \"mint\"",
            "audience = \"mint\"\nbind = \"not-an-addr\"",
        );
        assert!(matches!(
            parse_for_test(&toml, &[("volume-ro.json", "{}")]),
            Err(ConfigError::BadBindAddr { .. })
        ));
    }

    #[test]
    fn socket_path_selects_uds_verbatim() {
        let toml = SAMPLE.replace(
            "audience = \"mint\"",
            "audience = \"mint\"\nsocket = \"/run/mint.sock\"",
        );
        let c = parse_for_test(&toml, &[("volume-ro.json", "{}")]).expect("parse");
        assert_eq!(c.listener, Listener::Uds(PathBuf::from("/run/mint.sock")));
    }

    #[test]
    fn empty_socket_selects_uds_at_default_under_data_dir() {
        let toml = SAMPLE.replace(
            "audience = \"mint\"",
            "audience = \"mint\"\ndata_dir = \"/var/lib/mint\"\nsocket = \"\"",
        );
        let c = parse_for_test(&toml, &[("volume-ro.json", "{}")]).expect("parse");
        assert_eq!(
            c.listener,
            Listener::Uds(PathBuf::from("/var/lib/mint/mint.sock"))
        );
    }

    #[test]
    fn bind_and_socket_together_are_rejected() {
        let toml = SAMPLE.replace(
            "audience = \"mint\"",
            "audience = \"mint\"\nbind = \"127.0.0.1:8085\"\nsocket = \"/run/mint.sock\"",
        );
        assert!(matches!(
            parse_for_test(&toml, &[("volume-ro.json", "{}")]),
            Err(ConfigError::ConflictingListener)
        ));
    }

    #[test]
    fn unsafe_role_name_rejected_when_derived() {
        // No explicit policy_file, so the unsafe name flows into the
        // derived filename and must be caught — distinctly from an
        // explicit bad policy_file.
        let toml = SAMPLE
            .replace("policy_file = \"volume-ro.json\"\n", "")
            .replace("[tenant]", "roles_dir = \"mint_roles\"\n[tenant]")
            .replace("name = \"volume-ro\"", "name = \"../escape\"");
        assert!(matches!(
            Config::from_toml_str(&toml),
            Err(ConfigError::BadDerivedPolicyName { .. })
        ));
    }
}
